services:
  app:
    image: detection:latest
    container_name: detection
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_detection=1
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HOME=/app
      - DATA_DIR=/app/data 
    env_file:
      - .env
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - .:/app
      - /home/andreas/data:/app/data
      
#volumes:
#  appdata:
#    external: false